### ISSUE TITLE
eslint > 4.13 may break linting scripts

### ISSUE THREAD

**Issue by twjohnston** [ciena-blueplanet/ember-test-utils#117]
# BUG REPORT

## Expected Behavior
Linting should complete without error.

## Actual Behavior
Linting scripts may throw the following error and exit:
```
[...]/node_modules/eslint/lib/rules/no-unused-vars.js:410
            if (target.type === "VariableDeclarator") {
                      ^

TypeError: Cannot read property 'type' of undefined
```

## Possible Solution
Pin `eslint` to 4.13

## Steps to Reproduce
Depending on the script, running `npm i eslint@4.13.x` and then linting should resolve as expected. But, running `npm i eslint@4.14.x` and then linting may throw the above mentioned error.

## Environment
* ember-test-utils 6.0.0
* I am using these browsers:
  * [x] Latest Chrome
* [x] My version of `Node` is: 8.6.0
* [x] My version of `npm` is: 5.3.0
* [x] My OS is: OSX 10.13.4

**Comment by notmessenger** [comment]
It was determined that version 6.0.0 of this repos was being used, so as such this issue is being closed.
