### ISSUE TITLE
Upgrade ember-template-lint dependency

### ISSUE THREAD

**Issue by notmessenger** [ciena-blueplanet/ember-test-utils#92]
Will resolve

npm WARN deprecated lodash-node@2.4.1: This package is discontinued. Use lodash@^4.0.0.

└─┬ ember-test-utils@4.3.2
  └─┬ ember-template-lint@0.6.4
    └─┬ glimmer-engine@0.21.2

npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

└─┬ ember-test-utils@4.3.2
  └─┬ ember-template-lint@0.6.4
    └─┬ glimmer-engine@0.21.2
      ├─┬ emberjs-build@0.19.0
      │ └─┬ broccoli-string-replace@0.1.1
      │   └── minimatch@2.0.10

**Comment by juwara0** [comment]
Closed via: https://github.com/ciena-blueplanet/ember-test-utils/pull/96
